src/components/RecoverPassword.js
src/components/Register.js
src/firebase/firebase.js

agregue la funcion sendPasswordResetEmail de la documentacion de firebase al documento firebase.js y agregue un AddEventListener al boton de enviar* dentro del ./component/RecoverPassword para activar dicha funcion (faltan realizar pruebas)

reset password function

---

src/components/Login.js
src/styles(ref).css
src/styles.css

maquetacion del archivo Login.js con responsive

maquetacion 2.0 con responsive css

---

src/feed.html.html
src/feedstyle.css

footer listo! con reponsive

---

src/components/Feed.js
src/feed.html.html
src/feedstyle.css

ajustes en CSS y post template de usuarios en tiempo real

Erika up to date

---

src/components/Register.js

register ajuste

---

src/firebase/firebase.js

firebase ajuste

---

src/firebase/config.js

config ajuste

---

src/components/Feed.js
src/components/Login.js
src/feed.html.html

FEED.JS
se agregaron ID al textarea, boton de publicar, y al form (con estos IDs tenemos que jalarlos para hacer funcionar el form con el firestore)

cambio de textarea a form

---

src/components/Feed.js
src/firebase/firebase.js
src/styles.css

Se logro mostrar la colleccion 'posts' del firestore en el timeline del feed.
Falta:
agregar estilos
que se muestren en orden de publicacion 
que se publiquen al instante (onSnapShot)

Posts en feed

---

src/components/Feed.js
src/components/Login.js
src/firebase/firebase.js

correccion de errores en main
falta de semicolons, ubicacion de codigo

ajustes de errores

---

src/components/Feed.js
src/firebase/firebase.js

se movio la funcion para crear posts al firestore.js y se la importo al feed

mover la funcion de feed

---

src/components/Feed.js
src/firebase/firebase.js
src/main.js
src/styles.css

Se colocaron los botones a los posts de EDITAR y ELIMINAR.
Se ajusto un defecto del fondo de la pantalla donde se visualizaba color cortado.
Se recoloco la funcion de crear un post nuevamente dentro de la variable que contiene el feed.js.

agregar botones de edicion y reubicacion de la fun

---

src/components/Feed.js
src/firebase/config.js
src/firebase/firebase.js

Objetivo-> visualizar las fotos en los posts de cada usuario y visualizar la foto del usuario loggeado en su perfil 
inconvenientes-> 
Al momento teniamos una forma de recojer los datos que era peligroso (guardando todos los datos del usuario de manera remota) y esto no permitia poder modificar los datos en un futuro ya que no se usaban referencias, solo se empujaban los datos actuales de un lado a otro.
logrado->
-guardar los datos de ingreso con google
-proyectar estos datos en el timeline del usuario loggeado
-una base de datos en firestore usando referencias. De esta forma los datos se actualizan y se enlaza 'users' con 'post'. 
revisar->
-se agrego una funcion de permanencia de loggeo (setPersistence) que 'deberia' hacer que el usuario permanezca loggeado hasta que no se cierre la …

guardar datos de ingreso con google

---

src/components/Feed.js
src/styles.css

se ajusto la barra input search para que de mas espacio a la derecha donde va el nombre

ajustes del CSS para header

---

src/components/Feed.js
src/firebase/firebase.js
src/styles.css

Se creo una categoria dentro de la coleccion 'post' llamada 'liked_by' la cual es un arreglo y el evento del click en el icono del corazon hace que agregue el currentUser.uid a ese arreglo.

like y quitar like (por usuario) al hacer click

---

src/components/Feed.js

ya se logro poner un innertext con las actualizaciones del contador de likes al momento con snapshot

like visible en pantalla

---

src/components/Feed.js
src/firebase/firebase.js

Roxi avance Delete post

---

src/components/Feed.js
src/styles.css

se invirtio el orden del nombre del usuario conectado con su imagen
se agregaron estilos y ordeno el CSS

cambios al CSS para que se vea culz

---

src/components/Feed.js

alerta cuando se intente postear algo vacio
alerta cuando se envie un reporte

alertas de feed

---

src/components/Feed.js
src/firebase/firebase.js

Co-authored-by: Roxi Fiorella Ochoa García Co-authored-by: Tatiana Hernandez Avendaño

Re-organizacion del feed

---

src/components/Feed.js
src/firebase/firebase.js
src/styles.css

Fix feed posts

---

src/styles.css

Ajuste del CSS del boton [...]

Css de boton tres puntitos

---

src/components/Login.js
src/firebase/firebase.js

Todo listo para hacer testing! wohoooo
pendientes: 
Testing
ReadMe

ajustes de warnings y acomodado de funciones

---

src/components/Login.js
src/components/Register.js
src/firebase/firebase.js

register terminado
